/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './shared';
export declare const SharedModuleNgFactory: i0.NgModuleFactory<i1.SharedModule>;
export declare const RenderType_Header: i0.RendererType2;
export declare function View_Header_0(_l: any): i0.ɵViewDefinition;
export declare function View_Header_Host_0(_l: any): i0.ɵViewDefinition;
export declare const HeaderNgFactory: i0.ComponentFactory<i1.Header>;
export declare const RenderType_Footer: i0.RendererType2;
export declare function View_Footer_0(_l: any): i0.ɵViewDefinition;
export declare function View_Footer_Host_0(_l: any): i0.ɵViewDefinition;
export declare const FooterNgFactory: i0.ComponentFactory<i1.Footer>;
export declare const RenderType_Column: i0.RendererType2;
export declare function View_Column_0(_l: any): i0.ɵViewDefinition;
export declare function View_Column_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ColumnNgFactory: i0.ComponentFactory<i1.Column>;
export declare const RenderType_ColumnHeaderTemplateLoader: i0.RendererType2;
export declare function View_ColumnHeaderTemplateLoader_0(_l: any): i0.ɵViewDefinition;
export declare function View_ColumnHeaderTemplateLoader_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ColumnHeaderTemplateLoaderNgFactory: i0.ComponentFactory<i1.ColumnHeaderTemplateLoader>;
export declare const RenderType_ColumnBodyTemplateLoader: i0.RendererType2;
export declare function View_ColumnBodyTemplateLoader_0(_l: any): i0.ɵViewDefinition;
export declare function View_ColumnBodyTemplateLoader_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ColumnBodyTemplateLoaderNgFactory: i0.ComponentFactory<i1.ColumnBodyTemplateLoader>;
export declare const RenderType_ColumnFooterTemplateLoader: i0.RendererType2;
export declare function View_ColumnFooterTemplateLoader_0(_l: any): i0.ɵViewDefinition;
export declare function View_ColumnFooterTemplateLoader_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ColumnFooterTemplateLoaderNgFactory: i0.ComponentFactory<i1.ColumnFooterTemplateLoader>;
export declare const RenderType_ColumnFilterTemplateLoader: i0.RendererType2;
export declare function View_ColumnFilterTemplateLoader_0(_l: any): i0.ɵViewDefinition;
export declare function View_ColumnFilterTemplateLoader_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ColumnFilterTemplateLoaderNgFactory: i0.ComponentFactory<i1.ColumnFilterTemplateLoader>;
export declare const RenderType_TemplateLoader: i0.RendererType2;
export declare function View_TemplateLoader_0(_l: any): i0.ɵViewDefinition;
export declare function View_TemplateLoader_Host_0(_l: any): i0.ɵViewDefinition;
export declare const TemplateLoaderNgFactory: i0.ComponentFactory<i1.TemplateLoader>;
export declare const RenderType_Row: i0.RendererType2;
export declare function View_Row_0(_l: any): i0.ɵViewDefinition;
export declare function View_Row_Host_0(_l: any): i0.ɵViewDefinition;
export declare const RowNgFactory: i0.ComponentFactory<i1.Row>;
export declare const RenderType_HeaderColumnGroup: i0.RendererType2;
export declare function View_HeaderColumnGroup_0(_l: any): i0.ɵViewDefinition;
export declare function View_HeaderColumnGroup_Host_0(_l: any): i0.ɵViewDefinition;
export declare const HeaderColumnGroupNgFactory: i0.ComponentFactory<i1.HeaderColumnGroup>;
export declare const RenderType_FooterColumnGroup: i0.RendererType2;
export declare function View_FooterColumnGroup_0(_l: any): i0.ɵViewDefinition;
export declare function View_FooterColumnGroup_Host_0(_l: any): i0.ɵViewDefinition;
export declare const FooterColumnGroupNgFactory: i0.ComponentFactory<i1.FooterColumnGroup>;
export declare const RenderType_ColumnEditorTemplateLoader: i0.RendererType2;
export declare function View_ColumnEditorTemplateLoader_0(_l: any): i0.ɵViewDefinition;
export declare function View_ColumnEditorTemplateLoader_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ColumnEditorTemplateLoaderNgFactory: i0.ComponentFactory<i1.ColumnEditorTemplateLoader>;
